#!/usr/bin/env bash
# Memoria demo walkthrough — agent → mainnet → license
set -euo pipefail

echo "=== Memoria Demo (Monad mainnet) ==="
echo ""
echo "1. Start services:"
echo "   docker-compose up -d postgres qdrant"
echo "   cd backend && pip install -r requirements.txt && uvicorn app.main:app --reload"
echo "   cd web && npm run dev"
echo ""
echo "2. Set PRIVATE_KEY in .env (must match wallet that owns repos)"
echo ""
echo "3. Agent flow (http://localhost:3000/agent):"
echo "   - Connect wallet on Monad mainnet (chain 143)"
echo "   - Create repo (LICENSED visibility)"
echo "   - Ask a question → Approve proposal → Register on mainnet"
echo ""
echo "4. Or CLI sync after approve:"
echo "   python scripts/onchain_ops.py sync --repo-id <uuid>"
echo ""
echo "5. Provenance tab: structural + content verification"
echo ""
echo "6. License (different wallet or same):"
echo "   UI: Mint MEM + Buy license on repository page"
echo "   CLI: python scripts/onchain_ops.py license --repo-id <uuid>"
echo ""
echo "7. Analytics: royalty / knowledge revenue"
echo ""
echo "Tagline: Cognition lives off-chain. Ownership lives on Monad."
